apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: chaos-delay-user-to-app
  namespace: default
spec:
  hosts:
    - productpage
  http:
    - match:
        - uri:
            prefix: /productpage
      fault:
        delay:
          percentage:
            value: 100
          fixedDelay: 7s
      route:
        - destination:
            host: productpage
            port:
              number: 9080
    - route:
        - destination:
            host: productpage
            port:
              number: 9080
