grafana:
  enabled: true
  service:
    type: NodePort
  adminPassword: prom-operator

prometheus:
  enabled: true
  prometheusSpec:
    retention: 2d
    resources:
      requests:
        memory: 256Mi
        cpu: 100m

alertmanager:
  enabled: false

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true

defaultRules:
  create: true
